<?php

namespace App\Http\Models\DataPasien;

use Illuminate\Database\Eloquent\Model;

class PasienRajal extends Model
{
protected $connection = 'rj';
protected $table = 'View_PasienActive';
protected $fillable=[
      'ID'
      ,'NoEpisode'
      ,'NoRegistrasi'
      ,'LokasiPasien'
      ,'NoMR'
      ,'Visit Date'
      ,'Unit'
      ,'Inpatient'
      ,'RoomID'
      ,'Lab'
      ,'X-Ray'
      ,'Group'
      ,'Doctor_1'
      ,'Doctor_2'
      ,'JamPraktek'
      ,'Diagnose1'
      ,'Diagnose2'
      ,'Meried'
      ,'Education'
      ,'Ocupation'
      ,'ReferedCategory'
      ,'ReferedBy'
      ,'StatusOut'
      ,'CaraKeluar'
      ,'Asuransi'
      ,'Perusahaan'
      ,'Billto'
      ,'Payment Type'
      ,'PaymentDate'
      ,'CardNumber'
      ,'BankName'
      ,'Exptmonth'
      ,'ExptYear'
      ,'Ammount'
      ,'PaymentCash'
      ,'PaymentCard'
      ,'Kasir'
      ,'Tax Rate'
      ,'Notes'
      ,'Tax Status'
      ,'Status ID'
      ,'StatusMRoutby'
      ,'StatusMRinby'
      ,'StMRout'
      ,'stMRin'
      ,'LabFlag'
      ,'RadiologiFlag'
      ,'ResepFlag'
      ,'ResepComplate'
      ,'LabComplate'
      ,'RadiologiComplate'
      ,'TS'
      ,'Operator'
      ,'CetakPS'
      ,'JamCetak'
      ,'Keterangan'
      ,'Batal'
      ,'tglBatal'
      ,'Status Name'
      ,'DesName'
      ,'NamaDokter'
      ,'PatientName'
      ,'Gander'
      ,'Golongandarah'
      ,'NamaUnit'
      ,'IDPasien'
      ,'Address'
      ,'NoPesertaBPJS'
      ,'ID_Card_number'
      ,'Antrian'
      ,'LoketAntrian'
      ,'Panggil'
      ,'Aktif'
      ,'jamPanggil'
      ,'Selesai'
      ,'foto'
      ,'FlagPanggil'
      ,'LokasiAntrian'
      ,'FisioterapiLunas'
      ,'RadiologiLunas'
      ,'LabLunas'
      ,'Operasi'
      ,'JenisOperasi'
      ,'PatientType'
      ,'TipePasien'
      ,'CodeAntrian'
      ,'DPJP_RawatInap'
      ,'statusPulang'
      ,'FisioterapiFlag'
      ,'RawatInap'
      ,'Mobile Phone'
      ,'TTV'
      ,'SOAP'
      ,'Fisio'
      ,'NoRegRI'
      ,'lock'
      ,'ResepLunas'
      ,'NamaAsuransi'
      ,'NamaPerusahaan'
      ,'ValueDiscount'
      ,'TerapiWicara'
      ,'OkupasiTerapi'
      ,'EKG'
      ,'Treadmill'
      ,'Spirometri'
      ,'Usia'
      ,'Date_of_birth'
    ];
    protected $hidden = ['TS'];
    public function  getAvatar()
    {
        if($this->Gander=='Laki - Laki')
        {
            return asset('/assets/images/user/01.jpg');
        }
            return asset('/assets/images/user/02.jpg');
    }
    
}
