<?php

namespace App\Http\Models\EMRIGD;

use App\Masterdata\Employee;
use Illuminate\Database\Eloquent\Model;

class IntegratedNote extends Model
{
    protected $connection = 'mr';
    protected $table = 'EMR_RWJ';
    protected $fillable =[
       'ID'
      ,'NoMR'
      ,'NoEpisode'
      ,'NoRegistrasi'
      ,'Tgl'
      ,'NamaPasien'
      ,'TD_Sistol'
      ,'TD_Distol'
      ,'FrekuensiNadi'
      ,'Suhu'
      ,'FrekuensiNafas'
      ,'SkorNyeri'
      ,'KeteranganNyeri'
      ,'ResikoJatuh'
      ,'BeratBadan'
      ,'TinggiBadan'
      ,'BMIScore'
      ,'LingkarKepala'
      ,'AlatBantu'
      ,'Prothesa'
      ,'Cacat'
      ,'CacatTubuh'
      ,'ADL'
      ,'RiwayatJatuh'
      ,'Ada_DS'
      ,'MenggunakanAB'
      ,'GayaBerjalan'
      ,'StatusMental'
      ,'SkorResikoJatuh'
      ,'KriteriaResikoJatuh'
      ,'NamaPerawat'
      ,'GCS'
      ,'GCS_E'
      ,'GCS_M'
      ,'GCS_V'
      ,'StatusPsikologis'
      ,'SP_Depresi'
      ,'SP_Takut'
      ,'SP_Agresif'
      ,'SP_Melukaidiri'
      ,'HE'
      ,'HambatanEdukasi'
      ,'HE_bahasa'
      ,'HE_cacat'
      ,'HE_Penglihatan'
      ,'HE_Pendengaran'
      ,'HE_Tidakada'
      ,'RiwayatPenyakit'
      ,'KeluhanPasien'
      ,'S_Anamnesa'
      ,'S_RPD'
      ,'O_TTV'
      ,'O_PemeriksaanFisik'
      ,'A_Diagnosa'
      ,'P_RencanaTatalaksana'
      ,'P_InstruksiNonMedis'
      ,'Terapi'
      ,'DiagnosaUtama'
      ,'DiagnosaSkunder1'
      ,'DiagnosaSkunder2'
      ,'DiagnosaSkunder3'
      ,'StatusGizi'
      ,'AlasanRawatInap'
      ,'Konsul'
      ,'AlasanDirujuk'
      ,'Edukasi'
      ,'Dokter'
      ,'foto'
      ,'TTV'
      ,'DiagnosaNyeri'
      ,'PlanNyeri'
      ,'ImplemenNyeri'
      ,'EvaluasiNyeri'
      ,'DiagnosaHipertermi'
      ,'PlanHipertermi'
      ,'ImplemenHipertermi'
      ,'EvalusaiHipertermi'
      ,'DiagnosaNafasTE'
      ,'PlanNafasTE'
      ,'ImplemenNafasTE'
      ,'EvaluasiNafasTE'
      ,'DiagnosaJNTE'
      ,'PlanJNTE'
      ,'ImplemenJNTE'
      ,'EvaluasiJNTE'
      ,'DiagnosaGPGas'
      ,'PlasGPGas'
      ,'ImplemenGPGas'
      ,'EvaluasiGPGas'
      ,'DiagnosaBCairan'
      ,'PlanBalanceCairan'
      ,'ImplemenBalanceCairan'
      ,'EvalBalanceCairan'
      ,'DiagnosaBNutrisi'
      ,'PlanBalanceNutrisi'
      ,'ImplemenBalanceNutrisi'
      ,'EvalBalanceNutrisi'
      ,'DiagnosaGPerfusi'
      ,'PlanGPerfusi'
      ,'ImplemenGPerfusi'
      ,'EvalGPerfusi'
      ,'StatusHamil'
      ,'Gravida'
      ,'Para'
      ,'Abortus'
      ,'HPHT'
      ,'HPL'
      ,'CatatanKehamilan'
      ,'UsiaKehamilan'
      ,'OrderEndoscopy'
      ,'OrderRadiologi'
      ,'OrderEKG'
      ,'OrderFisioterapi'
      ,'OrderCathlab'
      ,'OrderLab'
      ,'KEP_PTP'
      ,'KEP_PO'
      ,'KEP_MN'
      ,'KEP_KD'
      ,'KEP_PD'
      ,'KEP_AM'
      ,'KEP_TR'
      ,'KEP_Laktasi'
      ,'KEP_KB'
      ,'KEP_SEKS'
      ,'KEP_LOP'
      ,'KEP_Nifas'
      ,'KEP_Persalinan'
      ,'KEP_PUC'
      ,'KEP_PSL'
      ,'KEP_PT'
      ,'KEP_TPP'
      ,'NamaUser'
      ,'GroupUser'
      ,'Batal'
      ,'SBAR'
      ,'TglSBAR'
      ,'YgMelapor'
      ,'PenerimaLaporan'
      ,'Saksi'
      ,'StatusCPPT'
      ,'CatatanDPJP'
      ,'Lockdata'
      ,'Hapus'
      ,'DihapusOleh'
      ,'AlasanHapus'
      ,'Konsultasi'
      ,'Images'
      ,'StatusKonsul'
      ,'KesimpulanKonsul'
      ,'ID_Req_Konsul'
      ,'Visit'
    ];


    public function  getAvatar()
    {   
        //$avtr = Employee::where('First Name','=',$this->NamaUser)->take(1)->get();
        //dd($avtr);
        // if($this->GroupUser == 'Dokter'){ 
          return asset('/assets/Avatar/'.$this->NamaUser.'.jpg');
        // }
        //   return asset('/assets/Avatar/dr7.png');  
        
        // elseif($this->GroupUser=='Perawat'){
        // return asset('/assets/Avatar/perawat.png'); 
        // }
        // return asset('/assets/Avatar/farmasi.png'); 
    }
}
